import turtle
import random


screen = turtle.Screen()
screen.screensize(800,800)
screen.bgcolor('lightsteelblue')

t_ground =turtle.Turtle()
t_ground.speed(0)
t_ground.fillcolor('snow1')
t_ground.penup()
t_ground.goto(-1000,-100)
t_ground.pendown()
t_ground.pencolor('snow1')
t_ground.begin_fill()
t_ground.goto(1000,-100)
t_ground.goto(100,-1000)
t_ground.goto(-1000,-1000)
t_ground.goto(-1000,-100)
t_ground.end_fill()
t_ground.hideturtle()

#======================= SNOW ================================

t = turtle.Turtle()
t.speed(0)
t.pensize(5)
for i in range(400):
    t.pencolor('snow')
    x= random.randint(-1000,1000)
    y = random.randint(-100,600)
    t.penup()
    t.goto(x,y)
    t.pendown()
    t.dot()
t.hideturtle()

#======================= TREE ONE ================================


t_trunk =turtle.Turtle()
t_trunk.speed(0)
t_trunk.penup()
t_trunk.pencolor('saddlebrown')
t_trunk.goto(195,-50)
t_trunk.pendown()
t_trunk.pensize(30)
t_trunk.goto(195, -90)
t_trunk.hideturtle()


tree =turtle.Turtle()
tree.speed(0)
tree.pencolor('DarkGreen')
tree.fillcolor('DarkGreen')
tree.penup()
tree.goto(195,70)
tree.pendown()
tree.begin_fill()
tree.goto(125,-50)
tree.goto(265,-50)
tree.goto(195,70)
tree.end_fill()

tree.penup()
tree.goto(195,100)
tree.pendown()
tree.begin_fill()
tree.goto(150,30)
tree.goto(240,30)
tree.goto(195,100)
tree.end_fill()

tree.penup()
tree.goto(170,30)
tree.pendown()
tree.goto(220,30)
tree.hideturtle()


#======================= TREE TWO ================================
trunk =turtle.Turtle()
trunk.speed(0)
trunk.penup()
trunk.pencolor('saddlebrown')
trunk.goto(-195,-50)
trunk.pendown()
trunk.pensize(30)
trunk.goto(-195, -90)
trunk.hideturtle()



tree =turtle.Turtle()
tree.speed(0)
tree.pencolor('DarkGreen')
tree.fillcolor('DarkGreen')
tree.penup()
tree.goto(-195,70)
tree.pendown()
tree.begin_fill()
tree.goto(-125,-50)
tree.goto(-265,-50)
tree.goto(-195,70)
tree.end_fill()

tree.penup()
tree.goto(-195,100)
tree.pendown()
tree.begin_fill()
tree.goto(-150,30)
tree.goto(-240,30)
tree.goto(-195,100)
tree.end_fill()

tree.penup()
tree.goto(-170,30)
tree.pendown()
tree.goto(-220,30)
tree.penup()
tree.hideturtle()

star =turtle.Turtle()
star.speed(0)
shift_x = 195
shift_y = -110

star.pencolor("goldenrod3")
star.fillcolor("gold1")
star.penup()
star.begin_fill()
star.goto(-30+shift_x,220+shift_y)
star.pendown()
star.goto(30+shift_x,220+shift_y)
star.goto(-20+shift_x,190+shift_y)
star.goto(0+shift_x,240+shift_y)
star.goto(20+shift_x,190+shift_y)
star.goto(-30+shift_x,220+shift_y)
star.end_fill()


shift_x = -195
shift_y = -110

star.pencolor("goldenrod3")
star.fillcolor("gold1")
star.penup()
star.begin_fill()
star.goto(-30+shift_x,220+shift_y)
star.pendown()
star.goto(30+shift_x,220+shift_y)
star.goto(-20+shift_x,190+shift_y)
star.goto(0+shift_x,240+shift_y)
star.goto(20+shift_x,190+shift_y)
star.goto(-30+shift_x,220+shift_y)
star.end_fill()
star.hideturtle()
#======================= Snowman ================================

snow =turtle.Turtle()
snow.speed(0)
snow.pencolor('snow3')
snow.fillcolor('snow1')
snow.penup()
snow.goto(-20,-100)
snow.pendown()
snow.begin_fill()
snow.circle(50)
snow.end_fill()

snow.penup()
snow.goto(-20,-20)
snow.pendown()
snow.begin_fill()
snow.circle(40)
snow.end_fill()

snow.penup()
snow.goto(-20,40)
snow.pendown()
snow.begin_fill()
snow.circle(30)
snow.end_fill()
snow.hideturtle()

####################### HAT ############
hat =turtle.Turtle()
hat.speed(0)
hat.pencolor('black')
hat.fillcolor('black')
hat.penup()
hat.goto(-20,98)
hat.pendown()
hat.begin_fill()
hat.goto(-60,98)
hat.goto(20,98)
hat.goto(20,110)
hat.goto(-60,110)
hat.goto(-60,98)
hat.end_fill()
hat.penup()
hat.goto(-50,110)
hat.pendown()
hat.begin_fill()
hat.goto(-50,140)
hat.goto(5,140)
hat.goto(5,110)
hat.goto(-50,110)
hat.end_fill()
hat.hideturtle()

#======================= pond ================================

pond =turtle.Turtle()
pond.speed(0)
pond.pencolor('lightblue')
pond.fillcolor('lightblue')
pond.penup()
pond.goto(-400,-400)
pond.pendown()
pond.begin_fill()
pond.circle(100)
pond.end_fill()
pond.penup()
pond.goto(-300,-350)
pond.pendown()
pond.begin_fill()
pond.circle(100)
pond.end_fill()
pond.penup()
pond.goto(-200,-400)
pond.pendown()
pond.begin_fill()
pond.circle(100)
pond.end_fill()
pond.penup()
pond.goto(-369,-450)
pond.pendown()
pond.begin_fill()
pond.circle(100)
pond.end_fill()
pond.penup()
pond.goto(-200,-450)
pond.pendown()
pond.begin_fill()
pond.circle(100)
pond.end_fill()
pond.penup()
pond.goto(400,-400)
pond.pendown()
pond.begin_fill()
pond.circle(100)
pond.end_fill()
pond.penup()
pond.goto(300,-350)
pond.pendown()
pond.begin_fill()
pond.circle(100)
pond.end_fill()
pond.penup()
pond.goto(200,-400)
pond.pendown()
pond.begin_fill()
pond.circle(100)
pond.end_fill()
pond.penup()
pond.goto(369,-450)
pond.pendown()
pond.begin_fill()
pond.circle(100)
pond.end_fill()
pond.penup()
pond.goto(200,-450)
pond.pendown()
pond.begin_fill()
pond.circle(100)
pond.end_fill()
pond.penup()
pond.goto(300,-400)
pond.pendown()
pond.begin_fill()
pond.circle(100)
pond.end_fill()
pond.penup()
pond.goto(200,-350)
pond.pendown()
pond.begin_fill()
pond.circle(100)
pond.end_fill()
pond.penup()
pond.goto(100,-400)
pond.pendown()
pond.begin_fill()
pond.circle(100)
pond.end_fill()
pond.penup()
pond.goto(269,-450)
pond.pendown()
pond.begin_fill()
pond.circle(100)
pond.end_fill()
pond.penup()
pond.goto(100,-450)
pond.pendown()
pond.begin_fill()
pond.circle(170)
pond.end_fill()
pond.penup()
pond.goto(200,-400)
pond.pendown()
pond.begin_fill()
pond.circle(100)
pond.end_fill()
pond.penup()
pond.goto(100,-350)
pond.pendown()
pond.begin_fill()
pond.circle(100)
pond.end_fill()
pond.penup()
pond.goto(50,-400)
pond.pendown()
pond.begin_fill()
pond.circle(140)
pond.end_fill()
pond.penup()
pond.goto(169,-450)
pond.pendown()
pond.begin_fill()
pond.circle(100)
pond.end_fill()
pond.penup()
pond.goto(500,-450)
pond.pendown()
pond.begin_fill()
pond.circle(100)
pond.end_fill()
pond.pendown()
pond.begin_fill()
pond.circle(170)
pond.end_fill()
pond.penup()
pond.goto(-50,-400)
pond.pendown()
pond.begin_fill()
pond.circle(100)
pond.end_fill()
pond.penup()
pond.goto(-169,-450)
pond.pendown()
pond.begin_fill()
pond.circle(100)
pond.end_fill()
pond.penup()
pond.penup()
pond.goto(-269,-450)
pond.pendown()
pond.begin_fill()
pond.circle(170)
pond.end_fill()
pond.penup()
pond.penup()
pond.goto(-60,-470)
pond.pendown()
pond.begin_fill()
pond.circle(170)
pond.end_fill()
pond.penup()
pond.goto(-90,-470)
pond.pendown()
pond.begin_fill()
pond.circle(170)
pond.end_fill()
pond.penup()
pond.goto(60,-470)
pond.pendown()
pond.begin_fill()
pond.circle(170)
pond.end_fill()
pond.penup()
pond.goto(90,-470)
pond.pendown()
pond.begin_fill()
pond.circle(170)
pond.end_fill()
pond.penup()
pond.goto(-100,-470)
pond.pendown()
pond.begin_fill()
pond.circle(170)
pond.end_fill()
pond.penup()
pond.goto(-100,-470)
pond.pendown()
pond.begin_fill()
pond.circle(170)
pond.end_fill()
pond.penup()
pond.goto(-270,-470)
pond.pendown()
pond.begin_fill()
pond.circle(170)
pond.end_fill()
pond.penup()
pond.goto(-370,-470)
pond.pendown()
pond.begin_fill()
pond.circle(170)
pond.end_fill()
pond.penup()
pond.goto(-570,-470)
pond.pendown()
pond.begin_fill()
pond.circle(170)
pond.end_fill()

#======================= Writing ================================
word = turtle.Turtle()
word.speed(0)
word.penup()
word.goto(0,300)
word.pendown()
word.write("Winter Wonderland",font=("Garamond",40, "bold"),align="center")
word.hideturtle()

#======================= skater ================================
s = turtle.Turtle()
s.speed(0)
s.pensize(8)
s.penup()
s.goto(-200,-200)
s.pendown()
s.goto(-100,-200)
s.goto(-100,-150)
s.goto(0,-150)
s.goto(-60,-100)
s.goto(-100,-150)
s.goto(-40,-220)
s.goto(-40,-300)
s.penup()
s.goto(0,-150)
s.pendown()
s.goto(0,-220)
s.penup()
s.goto(0,-150)
s.setheading(270)
s.pendown()
s.circle(25)

s.penup()
s.goto(-125,-125)
s.pendown()
s.goto(75,-300)
s.goto(125,-300)
s.penup()
s.pensize(4)
s.goto(118,-316)
s.pendown()
s.begin_fill()
s.circle(9)
s.end_fill()
s.hideturtle()

#last line of code
turtle.done()